### ISSUE TITLE
PyInstaller fails to produce a working Windows executable since the adoption of PyCryptodome

### ISSUE THREAD

**Issue by redion1992** [raffam/eurosportplayer-dl#5]
```
Traceback (most recent call last):
  File "eurosportplayer-dl.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\winprograms\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "Crypto\Cipher\__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\winprograms\python3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "Crypto\Cipher\_mode_ecb.py", line 47, in <module>
  File "Crypto\Util\_raw_api.py", line 300, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp37-win32.pyd': Failed to load dynlib/dll 'C:\\Users\\David\\AppData\\Local\\Temp\\_MEI79282\\Crypto\\Util\\..\\Cipher\\_raw_ecb.cp37-win32.pyd'. Most probably this dynlib/dll was not found when the application was frozen., Trying '_raw_ecb.pyd': Failed to load dynlib/dll 'C:\\Users\\David\\AppData\\Local\\Temp\\_MEI79282\\Crypto\\Util\\..\\Cipher\\_raw_ecb.pyd'. Most probably this dynlib/dll was not found when the application was frozen.
[2916] Failed to execute script eurosportplayer-dl
```

This occurs even when calling the binary without any arguments.

**Comment by raffam** [comment]
it looks like the adoption of pycryptodome has broken pyinstaller. I included the experimental hooks for pycryptodome, but now I am experiencing a new problem for which I have asked for support here: https://github.com/pyinstaller/pyinstaller/issues/4212

let's see

**Comment by raffam** [comment]
There is now a working .exe file in the "Release" section
