### ISSUE TITLE
Fails on step 1

### ISSUE THREAD

**Issue by tk2** [raffam/eurosportplayer-dl#7]
Hi,
I really hope I can get this to work! This is an excellent project! I just tried to get it running but it seems to fail on the first step getting the client authentication key with the following:
********** STEP 1 **********
Traceback (most recent call last):
  File "../bin/eurosportplayer-dl-master/eurosportplayer-dl.py", line 897, in <module>
    main(args)
  File "../bin/eurosportplayer-dl-master/eurosportplayer-dl.py", line 672, in main
    client_api_key = get_client_api_key()
  File "../bin/eurosportplayer-dl-master/eurosportplayer-dl.py", line 388, in get_client_api_key
    client_api_key = re.search("\"clientApiKey\"(?:\s*):(?:\s*)\"(.*?)\"", r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Any ideas what is wrong?

Thomas

**Comment by raffam** [comment]
You would have to provide me a link

**Comment by tk2** [comment]
It is working now with no problems. When I tried it first, I was using it via proxy from the US so there were probably geo location issues too. 
Great tool - thanks.
